# Autor: AS

version: "3"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka-broker
    ports:
      - 9092:9092
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./hadoop/data:/opt/hadoop
    environment:
      - CLUSTER_NAME=bigdata_cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop/hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop/hadoop.env
    depends_on:
      - namenode

  spark-master:
    image: bde2020/spark-master:3.2.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - HADOOP_CONF_DIR=/etc/hadoop
      - SPARK_HOME=/spark
    volumes:
      - ./hadoop/data:/opt/hadoop
    depends_on:
      - namenode

  spark-worker-1:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  jupyter-notebook:
      image: jupyter/pyspark-notebook
      container_name: jupyter
      ports:
        - "8888:8888"
      depends_on:
        - spark-master
      volumes:
        - ./jupyter/data:/home/jovyan/work
      environment:
        - "SPARK_MASTER=spark://spark-master:7077"

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  kafka_data:
    driver: local

networks:
  default:
    external:
      name: bigdatanetwork